In [3]:
import numpy as np

In [5]:
# Задание 1
A = np.matrix([[1, 2, 1], [-2, 1, 1]])
B = np.matrix([[3, 1], [-1, 0], [2, 4]])
C = np.matrix([[-2, 2], [1, -1], [1, 2]])


In [6]:
# транспонируем первую матрицу чтобы была одинаковая размерность.
A.T + 2*B

matrix([[7, 0],
        [0, 1],
        [5, 9]])

In [7]:
B+2*C

matrix([[-1,  5],
        [ 1, -2],
        [ 4,  8]])

In [8]:
# Задание 2
np.reshape(([0,1]*4+[1,0]*4)*4, (8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])